### ISSUE TITLE
supergroups not updating if app is closed

### ISSUE THREAD

**Issue by legacychimera247** [CODeRUS/harbour-sailorgram#10]
as the title says supergroups only receive new messages if the app is already opened...if not it only load latest message...

**Comment by CODeRUS** [comment]
EXPLAIN! :dalek:

**Comment by legacychimera247** [comment]
if the app is closed and then i open the app, all supergroups will show no new messages at allor only latest message written...if the app is opened it receive messages normally...praticalluy if someone from a supergroup write something while the app is closed that message is lost as sailorgram will not show it (they are correctly shown in telegram anyway)

**Comment by CODeRUS** [comment]
never experienced this and can't reproduce.

**Comment by legacychimera247** [comment]
i've made screenshot to make you understand...this one is the same chat at the same time in sailorgram
https://1drv.ms/i/s!AlyMkCypv00qgrRE80iW0SAvB0lhCw
this one is the same chat in telegram for android
https://1drv.ms/i/s!AlyMkCypv00qgrRF42TeezQv8ucMHA

as you may see there are messages missing in sailorgram and generally it misses all of the messages when closed...

**Comment by CODeRUS** [comment]
i can't see your screenshots by these links

**Comment by legacychimera247** [comment]
sorry...here it is...this is sailorgram
https://1drv.ms/i/s!AlyMkCypv00qgrRG7bkNuChsv97nTw
this is telegram
https://1drv.ms/i/s!AlyMkCypv00qgrRHmRVSjzD0RDBSWg

**Comment by CODeRUS** [comment]
i see, but i never experienced this. don't even know how to understand what can be wrong.

**Comment by legacychimera247** [comment]
unfortunately this is present since dax versions and doing a clean reinstall didn't solve the issue...

**Comment by CODeRUS** [comment]
fixed in v0.9.7
