### ISSUE TITLE
sometimes replies are not shown

### ISSUE THREAD

**Issue by legacychimera247** [CODeRUS/harbour-sailorgram#15]
as you may see from the screen sometimes the replies box is just empty

https://1drv.ms/i/s!AlyMkCypv00qgrR9ONyFZmpqoA_22g

**Comment by CODeRUS** [comment]
what the difference with? https://github.com/CODeRUS/harbour-sailorgram/issues/10

**Comment by legacychimera247** [comment]
the difference is that i am talking about replies done wuth the reply button and not messages in general like 10 was

**Comment by CODeRUS** [comment]
if the message is not loaded because of #10 there is no content to display inside replies
