### ISSUE TITLE
When chat-header is disactivated (= invisible), chat window doesn't increase to upper edge of display

### ISSUE THREAD

**Issue by newbiequestion** [CODeRUS/harbour-sailorgram#9]
In first, thanks a lot for your great (!) work CODeRUS!!!

**There is only one little blemish:** In settings, if I disactivate the visibility of the _chat header_ to get it invisible, the chat windows size doesn't increase to the upper edge of the display. There will be a useless blank space above the chat window (what looks a bit astonishing)...

It would be lot better if the chat window could completely cover the whole display until the upper edge, avoiding that blank space from the previous header...

Thank you very much! :-)

**Comment by CODeRUS** [comment]
haha, funny bug, thanks :rofl:
